//
// Created by noy on 08/01/2020.
//
#include "Server.h"
#ifndef GENERALIZED_SERVER_SIDE_IMPLEMENTATION_MYSERIALSERVER_H
#define GENERALIZED_SERVER_SIDE_IMPLEMENTATION_MYSERIALSERVER_H


class MySerialServer : public Server
{
};


#endif //GENERALIZED_SERVER_SIDE_IMPLEMENTATION_MYSERIALSERVER_H
