#ifndef GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SEARCHERSTACK_H
#define GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SEARCHERSTACK_H


class SearcherStack {

};


#endif //GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SEARCHERSTACK_H
