//
// Created by noy on 12/01/2020.
//

#ifndef GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SOLUTION_H
#define GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SOLUTION_H


class Solution {

};


#endif //GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SOLUTION_H
