//
// Created by noy on 08/01/2020.
//

#ifndef GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SOLVER_H
#define GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SOLVER_H


class Solver {

};


#endif //GENERALIZED_SERVER_SIDE_IMPLEMENTATION_SOLVER_H
